language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - "pip install ."
  - "pip install coverage"
script:
  - "python -m doctest README.md"
  - "coverage run --source parseable setup.py test"
after_success:
    - "bash <(curl -s https://codecov.io/bash)"
sudo: false
